### ISSUE TITLE
Baidu翻译api接口已经失效

### ISSUE THREAD

**Issue by DaPoHou** [UlionTse/translators#10]
http://api.fanyi.baidu.com/doc/21
新的api接口
https://fanyi-api.baidu.com/api/trans/vip/translate

**Comment by UlionTse** [comment]
不好意思，典型的商用api接口并不是我能提供的，请付费购买。您不能调用的，我这边都能调用，建议您不要频繁调用，谢谢。
<img width="501" alt="屏幕快照 2020-04-01 下午1 43 08" src="https://user-images.githubusercontent.com/14334826/78103227-f1a22e00-741e-11ea-9ae4-16d42934ac29.png">

**Comment by DaPoHou** [comment]
这不是商业接口不。通用，免费的。
我的错误提示是Baidu api路径错误。
在此之前，并没有使用过百度API。

包括之前Alibaba 和bing不能使用，我之前在自己服务器上练习python，绝未进行任何频繁调用。

**Comment by DaPoHou** [comment]
> 不好意思，典型的商用api接口并不是我能提供的，请付费购买。您不能调用的，我这边都能调用，建议您不要频繁调用，谢谢。
> <img alt="屏幕快照 2020-04-01 下午1 43 08" width="501" src="https://user-images.githubusercontent.com/14334826/78103227-f1a22e00-741e-11ea-9ae4-16d42934ac29.png">
我在多台服务器测试均报错（均是首次测试）
另外，您有尝试过全新安装translators库后测试吗？我觉得是不是从pip安装才会出现这些情况？
谢谢！

**Comment by UlionTse** [comment]
@DaPoHou 根据你提供的401报错信息，确认应该是你的服务器环境导致的。你可以在你的笔记本尝试。具体401情况，参考[此博文](https://www.cnblogs.com/eslovez/p/12111746.html)。

**Comment by DaPoHou** [comment]
> @DaPoHou 根据你提供的401报错信息，确认应该是你的服务器环境导致的。你可以在你的笔记本尝试。具体401情况，参考[此博文](https://www.cnblogs.com/eslovez/p/12111746.html)。

非常感谢您的解答。你有尝试过重新安装库，并测试吗？
我在三台服务器上测试均是这样。
都是直接使用apt install从python 3.5升级到3.7.
并更新/user/bin/python3软连接。

**Comment by DaPoHou** [comment]
我在win10商店了装了Python3.8，确实是正常的。
我在Ubuntu上，卸载了python3/pip，重新安装，错误仍然存在。

**Comment by DaPoHou** [comment]
![debug](https://user-images.githubusercontent.com/26761596/78419754-91f48e80-767b-11ea-9682-58498c0afcc6.PNG)

print(self.api_url, self.host_headers, form_data, proxies)
```
https://cn.bing.com/ttranslatev3?isVertical=1&&IG=3AA4A8BD3910450F8F86534592555ACA&IID=translator.5028.1 {'Referer': 'h
ttps://cn.bing.com/Translator', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gec
ko) Chrome/55.0.2883.87 Safari/537.36'} {'text': '仰天长啸，壮怀激烈。', 'fromLang': 'auto-detect', 'to': 'en'} None
```
 print(r)
`<Response [200]>`

print(data)
None

**Comment by UlionTse** [comment]
@DaPoHou 我上传模块库之前肯定是测试的，但一般不会在各个环境去测试，测试一般是测程序本身的代码问题，所以没有在Linux上进行测试。我解读一下就是说，我所有的接口都是对应各个浏览器网页版免费翻译的接口，就是你在网页上交互翻译的那个，所以401就是说某些网页版接口会知道你并没有在浏览器环境下去使用，类似反爬虫策略一样。
