### ISSUE TITLE
[Bug]: Google Translate TypeError for long texts that end with full stop

### ISSUE THREAD

**Issue by freddyheppell** [UlionTse/translators#100]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

When translating a text with Google Translate, I'm getting the TypeError shown below. I've debugged the code and it's happening because the list at `data[1][0][0][5]` contains an additional entry with `None` as the text at the end. 

![image](https://user-images.githubusercontent.com/1475568/206424120-952b09be-ad60-4a08-8b1d-cef45371c45c.png)

The text I am translating is 4,768 characters long. If I instead translate `text[:4765]`, it works. Running `text[4765:]` gives `.\n\n`. Even if I run `strip()` on the text, it still errors so it appears to be caused by the "." at the end of the sentence.

### APP Version

5.5.3

### Python Version

>=3.6, <=3.8

### Runtime Environment

Linux Ubuntu

### Country/Region

UK

### Relevant log output

```sh
File ~/mambaforge/envs/translate/lib/python3.8/site-packages/translators/server.py:2787, in TranslatorsServer.translate_text(self, query_text, translator, from_language, to_language, **kwargs)
   2785 if translator not in self.translators_pool:
   2786     raise TranslatorError
-> 2787 return self.translators_dict[translator](query_text=query_text, from_language=from_language, to_language=to_language, **kwargs)

File ~/mambaforge/envs/translate/lib/python3.8/site-packages/translators/server.py:95, in Tse.time_stat.<locals>._wrapper(*args, **kwargs)
     93     sys.stderr.write(f'CostTime(function: {func.__name__[:-4]}): {cost_time}s\n')
     94     return result
---> 95 return func(*args, **kwargs)

File ~/mambaforge/envs/translate/lib/python3.8/site-packages/translators/server.py:218, in Tse.check_query.<locals>._wrapper(*args, **kwargs)
    215     return func(*tuple(new_args), **kwargs)
    217 query_text = check_query_text(kwargs.get('query_text'), if_ignore_empty_query, if_ignore_limit_of_length, limit_of_length)
--> 218 return func(*args, **{**kwargs, **{'query_text': query_text}})

File ~/mambaforge/envs/translate/lib/python3.8/site-packages/translators/server.py:519, in GoogleV2.google_api(self, query_text, from_language, to_language, **kwargs)
    517 time.sleep(sleep_seconds)
    518 self.query_count += 1
--> 519 return {'data': data} if is_detail_result else ''.join([x[0] for x in (data[1][0][0][5] or data[1][0])])

TypeError: sequence item 41: expected str instance, NoneType found
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
@freddyheppell 
<img width="376" alt="translators_google_debug_0" src="https://user-images.githubusercontent.com/14334826/206437093-31fc84b1-2d45-4f34-af7a-74d072eda4fe.PNG">

**Comment by freddyheppell** [comment]
I have also been unable to reproduce it on short texts, or actually some other texts close to the character limit.

However, I get this error _every time_ on this text, on multiple different machines. [Here is a Colab notebook](https://colab.research.google.com/drive/1nG0h8JHoKp22PQqNlY94gWnJcNbIhltL?usp=sharing) with the text showing the error

**Comment by UlionTse** [comment]
My backparse of Google Translate may not have been accurate enough, since it was too confusing to read, with stars in my eyes.

**Comment by freddyheppell** [comment]
I think you can fix this by just removing the final entry of the list if it has None instead of the text. All the translated text I was expecting is in the previous lines, so Google Translate has just added this line for no obvious reason.

**Comment by UlionTse** [comment]
`pip install --upgrade translators==5.5.4` or `conda install translators=5.5.4` please.

**Comment by freddyheppell** [comment]
Works fine! Only thing I have noticed is that I think the list should be joined on `" "` instead of `""`, because it seems Google gets rid of the space after the full stop.

<img width="487" alt="An Italian sentence with spaces after the full stops" src="https://user-images.githubusercontent.com/1475568/206903379-14b36f71-e2c4-4376-9355-2c07d9dc1abc.png">

<img width="487" alt="The English translation of the sentence, without spaces after the full stops" src="https://user-images.githubusercontent.com/1475568/206903356-ef764033-a2fe-4df8-b35b-62dc290cf650.png">

In the Google Translate web interface, each of the items from this list are put into a `<span>` tag and then they insert whitespace _between_ them, so joining on `" "` is basically the Python equivalent of that

<img width="584" alt="Some HTML from Google Translate with a whitespace element between two spans" src="https://user-images.githubusercontent.com/1475568/206903564-7c0a90fb-5b50-4f52-a587-1e79dfe99416.png">
