### ISSUE TITLE
TranslatorError: [Bug]: 

### ISSUE THREAD

**Issue by yonglee7015** [UlionTse/translators#102]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

TranslatorError:  it seems cos of length of text limitation. 
df['Name_translator'] = df['Name'].apply(lambda x: ts.translate_text(x, translator='google',from_language ='en',to_language='zh'))
When I want to translator  a column en to zh. it raise this error. 

### APP Version

0.0.1(example)

### Python Version

3.9 (Default)

### Runtime Environment

Linux CentOS (Default)

### Country/Region

China

### Relevant log output

```sh
[/usr/local/lib/python3.8/dist-packages/translators/server.py](https://localhost:8080/#) in check_query_text(query_text, if_ignore_empty_query, if_ignore_limit_of_length, limit_of_length)
    192 
    193             if not isinstance(query_text, str):
--> 194                 raise TranslatorError
    195 
    196             query_text = query_text.strip()

TranslatorError:
```

### Screenshots

```Markdown
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
@yonglee7015 Attention input type
