### ISSUE TITLE
[Feature]:  Better Introduction

### ISSUE THREAD

**Issue by PythonLinks** [UlionTse/translators#103]
### Expect to happened

A feature I have expected ...
I am a bit confused.  There is no high level description. 
You mention all of these different translation services. 

I will get this wrong, but you need to say something like. 

This translators api uses a Node server to pretend to be an end user seeking translation services.  You can choose which free translation service you want to use.  First you have to check if that translation service translates the languages you want to translate in the country where you live.   You are also likely to get rate limited.  Sadly we do not know when those limits kick in, nor does the api rate limit you, you have to do that yourself.   

Nor does the api round robin the translation services, to prevent rate limiting. 

Anyhow some such high level description of how this software works would be most helpful.   

### Expected APP Version

a future version

### Expected Python Version

3.9

### Expected Runtime Environment

Other

### Country/Region

Poland

### Expected Output

```sh
Just a better introduction.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
Sorry for the long time.
If every free translation service doesn't provide relevant information, I can't help it. If you go to a paid service, I'm sure the official documentation is very detailed.
