### ISSUE TITLE
[Bug]: Bing Translators doesn't work

### ISSUE THREAD

**Issue by Shun-Calvin** [UlionTse/translators#104]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

It seems that the API of Bing is not working and no result can be shown if the translator is Bing.

### APP Version

5.5.5

### Python Version

3.9 (Default)

### Runtime Environment

Windows 10

### Country/Region

Hong Kong

### Screenshots

```Markdown
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
Roger that, Sir!

**Comment by UlionTse** [comment]
v5.5.6 please
