### ISSUE TITLE
[Bug]: AttributeError: module 'translators' has no attribute 'google'

### ISSUE THREAD

**Issue by sunny9495-dev** [UlionTse/translators#105]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

Iam getting this error when running on mac server 

```
AttributeError: module 'translators' has no attribute 'google'
```

### APP Version

5.5.5

### Python Version

3.9 (Default)

### Runtime Environment

MacOS

### Country/Region

US

### Relevant log output

```sh
AttributeError: module 'translators' has no attribute 'google'
```

### Screenshots

```Markdown
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
`translators.server.google()`
