### ISSUE TITLE
[Feature]: 可否增加字节跳动旗下火山翻译，这个和谷歌对比翻译质量相差不是很大，相对来说比较适用

### ISSUE THREAD

**Issue by twitf** [UlionTse/translators#106]
### Expect to happened

它的地址是：https://translate.volcengine.com/

### Expected APP Version

next newest version

### Expected Python Version

>=3.6 (Default)

### Expected Runtime Environment

NoArch (Default)

### Country/Region

Qatar(example)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
Roger that, Sir.

**Comment by twitf** [comment]
Is there any clue?

**Comment by UlionTse** [comment]
How did `_signature:` get it, this problem has not been solved.
