### ISSUE TITLE
[Bug]: 有道v1接口错误

### ISSUE THREAD

**Issue by azmiao** [UlionTse/translators#108]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

有道翻译v1的网页页面已经变动
`server.py`第738行的`get_language_map(self, host_html, **kwargs)`已经拿不到所有的语言字典了

暂时没发现其他获取语言字典的地方，v3那边限制1000字符，超出就会103错误，所以还是希望大佬修一修v1，不知道能不能修，实在不行，吧v1的语言校验写死也行（

### APP Version

5.5.6？

### Python Version

>=3.6, <=3.8

### Runtime Environment

Windows 10

### Country/Region

China

### Relevant log output

```sh
no log（）
```

### Screenshots

```Markdown
no screenshots
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mozbugbox** [comment]
暂时可以用 `zh-CHS` 代替 `zh` 作为中文代码。

**Comment by azmiao** [comment]
> 暂时可以用 `zh-CHS` 代替 `zh` 作为中文代码。

好像是也不行，我记得昨天测的时候他报错 `zh-CHS` ，如果我没记错的话，是因为在获取他网页上的可选语言列表的时候，由于网页变动，导致语言列表是空的，然后列表调用`pop('zh-CHS')`的时候抛出异常了，我现在是临时注释掉了校验语言是否在语言列表里的代码，这样倒是可以用

**Comment by UlionTse** [comment]
Why not use youdaoV3(default) interface?

<img width="269" alt="translators20230213_youdao" src="https://user-images.githubusercontent.com/14334826/218481355-794f7548-7842-4c23-aaa6-a17f866cc862.PNG">

**Comment by azmiao** [comment]
> Why not use youdaoV3(default) interface?
> 
> <img alt="translators20230213_youdao" width="269" src="https://user-images.githubusercontent.com/14334826/218481355-794f7548-7842-4c23-aaa6-a17f866cc862.PNG">

Because the v3 interface is limited to 1000 characters, and error 103 is reported when the character limit is exceeded, while v1 supports 5000 characters. I need about 3000+characters for translation

**Comment by UlionTse** [comment]
Otherwise, about `if not language_map == True`, temporary solution:
```python


_yd = ts.server.YoudaoV1()

lang_list = ['en', 'ru']  # languages you need
_yd.language_map = {}.fromkeys(lang_list, lang_list)
youdao = _yd.youdao_api
print(youdao('你好'))
```

**Comment by azmiao** [comment]
> Otherwise, about `if not language_map == True`, temporary solution:
> 
> ```python
> _yd = ts.server.YoudaoV1()
> 
> lang_list = ['en', 'ru']  # languages you need
> _yd.language_map = {}.fromkeys(lang_list, lang_list)
> youdao = _yd.youdao_api
> print(youdao('你好'))
> ```

Yes, I use it temporarily like this
