### ISSUE TITLE
[Feature]: Got tons of  http 429 errors

### ISSUE THREAD

**Issue by CobeBriant** [UlionTse/translators#109]
### Expect to happened

I have about 10k news of other languages, and I did use the package to handle my own data translation one by one , I think it triggered the error of http 429

### Expected APP Version

next newest version

### Expected Python Version

>=3.6 (Default)

### Expected Runtime Environment

NoArch (Default)

### Country/Region

Qatar(example)

### Expected Output

```sh
Dear team, 

My expectation is how could I get unblocked and use the tool normally again. could you help to unblock my ip ？
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
1. Shuffle and use different translator server
2. Reduce request frequency. Including parameters: sleep_seconds, timeout, proxies, update_session_after_seconds
3. Purchase paid service
