### ISSUE TITLE
应该增加一下调用频率相关的说明

### ISSUE THREAD

**Issue by 312shan** [UlionTse/translators#11]
这个包挺好用的，
一个小小的建议：应该增加一下调用频率相关的说明，比如间隔多长时间调用一次不会被block, 每天调用上限是多少？类似这方面的信息挺重要的。

**Comment by DaPoHou** [comment]
如果可以增加腾讯、baidu token设置更好了。
现在注册腾讯云、baidu每个月都是有免费额度的，基本上用不完。

**Comment by UlionTse** [comment]
@312shan @DaPoHou  我这边实现的就是你在浏览器网页上交互的翻译接口，每天调用上限应该是没有的，`sleep_seconds`参数建议至少大于1，具体应该是越大越随机越不容易被封，此库的目的并不建议有大量频繁的请求，因为这是商家免费善意的资源。若有大量频繁请求或商用目的，建议购买商家api服务。
