### ISSUE TITLE
[Feature]:add proxy pool

### ISSUE THREAD

**Issue by vincecarterhu** [UlionTse/translators#115]
### Expect to happened

I want use this proxy pool [address](https://github.com/jhao104/proxy_pool/) but is not  easy to add it

### Expected APP Version

next newest version

### Expected Python Version

>=3.6 (Default)

### Expected Runtime Environment

NoArch (Default)

### Country/Region

Qatar(example)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
```python
import random

your_proxy_pool = [{'http': '123.123'}, {'http': '456.456'}]
print(ts.translate_text(chs_text, proxies=random.choice(your_proxy_pool)))
```
