### ISSUE TITLE
[Feature]: Support for Mirai translate?

### ISSUE THREAD

**Issue by innyinny** [UlionTse/translators#119]
### Expect to happened

There is another free translation engine called https://miraitranslate.com/
it specializes in japanese, it seems to be very nice. according to reviewers/testers that compare engines: it's
second best behind DeepL for japanese

and unfortunately DeepL is very unreliable through the library because of captcha or weird errors or something

maybe this one could be a good choice for japanese to english

Thanks for your project, its very cool

### Expected APP Version

a future version

### Expected Python Version

>=3.6 (Default)

### Expected Runtime Environment

NoArch (Default)

### Country/Region

Japanese

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by innyinny** [comment]
nm i guess its only free for a very limited time without a trial..

thats a bummer..

**Comment by UlionTse** [comment]
Okay.

**Comment by UlionTse** [comment]
@innyinny Please upgrade to v5.7.0, but `marai` hasn't passed the test yet.
