### ISSUE TITLE
建议添加 DeepL 翻译接口

### ISSUE THREAD

**Issue by SeamasSun** [UlionTse/translators#12]
https://www.deepl.com/translator，无论是词组、日常用语、短文翻译，整体表现均很出色。

**Comment by UlionTse** [comment]
@SeamasSun 收到😉。

**Comment by UlionTse** [comment]
@SeamasSun Deepl has been added, and the version is updated to v4.5.0. welcome to download, update and use it.  By the way, deepl's translation speed is still very slow compared with other translators.
