### ISSUE TITLE
[GUI] Created GUI with this library

### ISSUE THREAD

**Issue by Azornes** [UlionTse/translators#120]
I created a translation program using this library. If anyone is interested in checking it out, I invite you to do so.
https://github.com/Azornes/ocrTranslator

Thank you for maintaining this library. It has helped me to create an application for comparing various technologies. I am truly grateful for your efforts.

If you wish, you may create a discussion in your repository for such information or other interesting topics, in order to avoid opening new issues. This approach could help to maintain a more organized and efficient process of addressing various topics.

**Comment by UlionTse** [comment]
OK.
