### ISSUE TITLE
[Bug]: 当用sogou批量翻译时返回一些奇怪的随机数，要怎么捕获处理，或者有没有建议的请求频率

### ISSUE THREAD

**Issue by firmianay** [UlionTse/translators#130]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

A bug happened!

### APP Version

latest

### Python Version

3.10

### Runtime Environment

Linux Ubuntu

### Country/Region

China

### Screenshots

```Markdown
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
Hello friend!
You can catch exceptions by getting the complete response data by using the parameter `is_detail_result=True`.

**Comment by firmianay** [comment]
我包装了一下，现在还行，中文不是ascii：
```
def translate(text: str):
    if text:
        with contextlib.suppress(Exception):
            result = translators.translate_text(text, translator='sogou')

        if not result.isascii():
            return result

    return ''
```
