### ISSUE TITLE
推荐加个翻译接口Deepl，翻译质量非常不错

### ISSUE THREAD

**Issue by DaPoHou** [UlionTse/translators#14]
https://www.deepl.com/translator

这个翻译网页接口是无限量的，而且翻译质量非常不错。

**Comment by UlionTse** [comment]
Hey @DaPoHou , I think the advice started in #12  😋

**Comment by DaPoHou** [comment]
是的，期待您的加入。赞一个！

**Comment by UlionTse** [comment]
@DaPoHou upgrade the version4.5.0, welcome to using it.
