### ISSUE TITLE
[Feature]: Return the chosen language (handy when using 'auto') 

### ISSUE THREAD

**Issue by ManuelSchneid3r** [UlionTse/translators#140]
It would be nice to know which language was chosen as source language when translated with 'auto'. A function `translate` that returns something like ['src_lang', 'dest_lang', 'translated_text'] would be awesome.

**Comment by UlionTse** [comment]
@ManuelSchneid3r Hello friend !
You can `pip install langdetect` or `pip install langid`.

**Comment by ManuelSchneid3r** [comment]
indeed this issue is covered by #139. ty, i'll join the dicsussion there.
