### ISSUE TITLE
[Bug]: "The `query_text` can't be empty!" in translate_html

### ISSUE THREAD

**Issue by Cabu** [UlionTse/translators#141]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

When translating an HTML content with translate_html, I get a "The `query_text` can't be empty!" because the pattern find empty string even if the HTML I send doesn't contain any. 

replacing in server.py the line 5326
```
sentence_list = list(set(pattern.findall(html_text)))
```
by
```
sentence_list = list(text for text in set(pattern.findall(html_text)) if text)
```

Solve my problem and as a side effect solve the TODO <code></code>

### APP Version

5.8.3

### Python Version

3.11

### Runtime Environment

Linux CentOS (Default)

### Country/Region

Belgium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
@Cabu https://github.com/UlionTse/translators/issues/130#issuecomment-1562749253
