### ISSUE TITLE
[Feature]: Translation services (eg Bing) easily rate limited

### ISSUE THREAD

**Issue by Cabu** [UlionTse/translators#143]
### Expect to happened

When translating a bunch of HTML pages with translate_html(), Bing is very quickly in Error due to rate limitation. 

1) Would it be possible to set default rate limits for the different providers?
2) Would it be possible if no provider is set to dispatch the translation requests on multiple providers allowing the translation (from->to) allowing better throughput while reducing the rate on each of them.

### Expected APP Version

a future version

### Expected Python Version

>=3.8 (Default)

### Expected Runtime Environment

NoArch (Default)

### Country/Region

Any

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
@Cabu The part2 of https://github.com/UlionTse/translators/issues/109#issuecomment-1427993673
