### ISSUE TITLE
[Bug]: Python 3 doesn't like re with Positive Lookbehind ?

### ISSUE THREAD

**Issue by Cabu** [UlionTse/translators#145]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

from: 
```
import re
html_text = '<p>sentence 1</p><p>sentence 2</p>'
pattern = re.compile("(?:^|(?<=>))([\\s\\S]*?)(?:(?=<)|$)")  # TODO: <code></code> <div class="codetext notranslate">
sentence_list = list(set(pattern.findall(html_text)))
```

In Python 2.7.18, the re module return:
```
sentence_list = ['sentence 1', 'sentence 2']
```

In Python 3.7.16 and 3.11.3, the re module return.
```
sentence_list = ['<p>sentence 1', '<p>sentence 2']
```

Simplifying the RE seems to work well:
```
        pattern = re.compile("(?:^|>)([\\s\\S]*?)(?:<|$)")  # TODO: <code></code> <div class="codetext notranslate">
```

I have opened a bug in cpython in case the problem come from them: https://github.com/python/cpython/issues/109579

### APP Version

5.8.3

### Python Version

3.11

### Runtime Environment

Linux CentOS (Default)

### Country/Region

Belgium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
@Cabu Friend, I think whether the parttern`>[\\s\\S]<` of greedy search is enough, even if it's not perfect. So try the new version 5.8.4

**Comment by UlionTse** [comment]
@Cabu The pattern is used twice, `findall` and `sub`, not only `findall`, so long long ago the pattern is complicated.
