### ISSUE TITLE
[Bug]: "Using region <name> server backend." printed on stdout

### ISSUE THREAD

**Issue by ManuelSchneid3r** [UlionTse/translators#147]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

This message is printed to stdout. Since this is a library it should be quiet unless i tell it to be verbose.

This makes problems in my app where I use logging categories. If users pass --quiet only warning and above are printed.

This library prints this message though

### APP Version

happens on all recent versoins

### Python Version

3.11

### Runtime Environment

Linux Ubuntu

### Country/Region

germany

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
@ManuelSchneid3r `pip install --upgrade translators==5.8.9`
