### ISSUE TITLE
[Feature] Batch Translation for Google Translate.

### ISSUE THREAD

**Issue by Senjar** [UlionTse/translators#15]
An option to batch translate multiple texts.

**Comment by UlionTse** [comment]
@Senjar Generally speaking, the total number of words in each translation should not exceed 5000.  A good batch partition of the article needs to consider translating more content at one time as much as possible, the integrity of the sentence itself in the partition area, and the integrity of the context in the partition area, but this is not what the library is going to do.

**Comment by Senjar** [comment]
What I'm trying to do is translate a list of sentences that are not related. I can combine them all up in a single string but then I can't split them back after the translation. I tried putting custom delimiters but sometimes they are lost for some reason in the translated text.

**Comment by UlionTse** [comment]
@Senjar Just like what you need, your current method is an efficient one. Maybe you just need to understand what delimiter is in the `to_language` context after translation in the `from_langauge` context. Another way is to translate a single sentence directly without merging. In this way, concurrency should be considered and the frequency of requests should be paid attention to. In addition, the third way is to use `is_detail_result=True`, there will be surprises.
