### ISSUE TITLE
[Bug]: Unable to find server backend.

### ISSUE THREAD

**Issue by dvdcjw** [UlionTse/translators#153]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

hey guys I'm trying to make a GUI program right now, I just don't want the user to touch the CLI.
Is there anyway to prevent this from happening?

### APP Version

5.8.9

### Python Version

3.11

### Runtime Environment

Windows 10

### Country/Region

China

### Relevant log output

```sh
\Lib\site-packages\translators\server.py:331: UserWarning: Unable to find server backend.
 warnings.warn('Unable to find server backend.\n\n')
Please input your server region need to visit:
eg: [Qatar, China, ...]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
@dvdcjw Hello friend,
Attention this ->https://github.com/UlionTse/translators/blob/c20c815ffe0ed75c551eef37d86055d8a8e435c7/translators/server.py#L307, you can add these codes first:
```python
import os

os.environ['translators_default_region'] = 'CN'
```
