### ISSUE TITLE
[Bug]: 504 Server Error: Gateway Time-out for url: https://aidemo.youdao.com/trans

### ISSUE THREAD

**Issue by FunnySaltyFish** [UlionTse/translators#156]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

https://aidemo.youdao.com/trans, Youdao has closed this website.

### APP Version

5.9.0

### Python Version

3.10

### Runtime Environment

Windows 10

### Country/Region

China

### Screenshots

```Markdown
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
@FunnySaltyFish Nope, bro. This url is api_url, not host_url. You know, api_url needs `post+payload` to request usually.
<img width="203" alt="translators_issue_156" src="https://github.com/UlionTse/translators/assets/14334826/8cd8f262-8360-49e1-91cb-4350720deeb9">

**Comment by FunnySaltyFish** [comment]
Thanks for replying. 

> This url is api_url, not host_url. 
Yeah, I know it. The error message is copied directly from my server's log. At the time I submitted this issue, the website displayed '502 Error' only and the `youdao` engine didn't work anymore, neither on the server nor on my local computer.

It looks like that was Youdao's issue at that time. The code works fine in my computer as well, now. I will run it on server and continue to observe its work status. I'll close the issue now.
