### ISSUE TITLE
[Bug]: 对省略号翻译的时候就会发生一些错误

### ISSUE THREAD

**Issue by aaawoshicaigou** [UlionTse/translators#158]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

A bug happened!
![PixPin_2024-04-16_21-49-39](https://github.com/UlionTse/translators/assets/116898395/1ad82420-da13-4117-b4fa-c454669f336b)
这样的错误有很多处，导致数据很难使用，请问有更稳定的翻译源吗，caiyun翻译大概200-300条时会拒绝访问，并且也有这样的错误，bing虽然较为稳定，但是会出错，其他的源我也尝试过，效果也不好

### APP Version

5.9.1(example)

### Python Version

3.9 (Default)

### Runtime Environment

Windows 10

### Country/Region

安徽省蚌埠市

### Screenshots

```Markdown
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aaawoshicaigou** [comment]
我用了几乎所有在中国能用的，目前感觉bing和iciba准确率较高，但是也都有一些问题，iciba有时候会少翻译一些东西，比如fifty thousand dollars 会少翻译fifty

**Comment by UlionTse** [comment]
@aaawoshicaigou 你的截图翻译除了‘kkkk’之外也没啥问题呀。并且你说的【很多错误】要举例且要能复现问题，不要主观评价。因为我也评价不了你说的东西是不是真的、对的、非常主观的。我只能解决可以复现的bug，且翻译服务有翻译质量问题不是一件轻松愉快、可以被理解的事吗？毕竟很多翻译服务商都有专门售卖的API服务，需要的就是你这种客户呀。所以免费翻译一般他们也不会优化的非常好。

**Comment by UlionTse** [comment]
@aaawoshicaigou 
<img width="589" alt="translators_158" src="https://github.com/UlionTse/translators/assets/14334826/516df41a-6cd3-498e-8f8b-0e0f76ff2949">

**Comment by aaawoshicaigou** [comment]
谢谢你的回复，确实就免费的api来说，有这样的效果已经很好了，是我要求太多了，我翻译的结果大概有1/10会有一些小问题，然后我通过自己手动更改改过来了，总之谢谢你，这边使我使用过程中最主要的错误截图，希望能给你一些帮助
![PixPin_2024-04-22_17-06-41](https://github.com/UlionTse/translators/assets/116898395/4ed57527-d90a-4b14-9797-7cf55ebbfedf)

![PixPin_2024-04-22_17-05-08](https://github.com/UlionTse/translators/assets/116898395/ffc0a2c5-6cc1-4f8a-add8-5a4f950f13d4)
[translated_data1.json](https://github.com/UlionTse/translators/files/15060390/translated_data1.json)

**Comment by UlionTse** [comment]
Okay，thanks for your reply, too.
