### ISSUE TITLE
[Feature]: Hint Unit for timeout var in preaccelerate_and_speedtest

### ISSUE THREAD

**Issue by dvdcjw** [UlionTse/translators#160]
### Expect to happened

Could you give a default value or a unit hint for the timeout? I have no idea whether it's in seconds or ms

### Expected APP Version

next newest version

### Expected Python Version

3.10

### Expected Runtime Environment

Windows 10

### Country/Region

Qatar(example)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
@dvdcjw Hello, bro.
Seconds, From here, https://docs.python-requests.org/en/latest/user/quickstart/#timeouts.
