### ISSUE TITLE
[Bug]: yandex http error 400

### ISSUE THREAD

**Issue by Dimoks** [UlionTse/translators#162]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

`ts.translate_text('「――――――」', translator='yandex', from_language='auto', to_language='ru')`

Causes error 400.

### APP Version

5.9.2

### Python Version

3.12

### Runtime Environment

Windows 10

### Country/Region

Russia

### Relevant log output

```sh
File "C:\Program Files\Python312\Lib\site-packages\translators\server.py", line 5555, in translate_text
    return self.translators_dict[translator](query_text=query_text, from_language=from_language, to_language=to_language, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\translators\server.py", line 117, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\translators\server.py", line 288, in _wrapper
    return func(*args, **{**kwargs, **{'query_text': query_text}})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\translators\server.py", line 2392, in yandex_api
    data = self.get_request_data(ss=self.session, method='translate', params=params, timeout=timeout, proxies=proxies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\translators\server.py", line 2334, in get_request_data
    r.raise_for_status()
  File "C:\Program Files\Python312\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://browser.translate.yandex.net/api/v1/tr.json/translate?srv=browser_video_translation&text=%E3%80%8C%E2%80%95%E2%80%95%E2%80%95%E2%80%95%E2%80%95%E2%80%95%E3%80%8D&lang=-ru
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Dimoks** [comment]
https://github.com/UlionTse/translators/blob/13564ea8c7f6844aeabab169f4ac87f396025b19/translators/server.py#L2389-L2391
Between them I added
```
        if not from_language:
            from_language = 'ja'
```

**Comment by UlionTse** [comment]
@Dimoks `pip install --upgrade translators==5.9.3`

**Comment by Dimoks** [comment]
'zh'? It'll do.
I noticed that if you need to make several translations in a row (you can’t combine them into one request), this is done very slowly. And all due to the fact that several requests are made to the site each time.
To speed up the work, I had to disable the get_language_map, check_language requests, and specify the language directly.
It is better to keep the list of available languages ​​locally, like in a deep translator.

**Comment by UlionTse** [comment]
@Dimoks 
Bro, if you read the source code carefully, it is obvious that some of your statements are not true.
1. Functions such as get_language_map() are only run once, not for each request.
2. The check_language() function is necessary for each request, and the time spent is negligible.
3. Content merging requests, that's what you should do, not me.

**Comment by Dimoks** [comment]
ts.translate_text(en_text, translator='yandex', from_language='en', to_language='ru')
ts.translate_text(en_text, translator='yandex', from_language='en', to_language='ru')
is get_language_map() called once? More like two.
And with from_language='auto', to_language='ru' there will be three. Site requests are slow. I need to make a lot of requests. In my case, they cannot be combined at all.

**Comment by UlionTse** [comment]
@Dimoks 
Do you think that you can slander others' code without any bottom line because of slow access? Have you really understood the response speed of Yandex in web service requests? Did you read the third point of my answer last time carefully? I will answer you again, I hope you can understand it.
<img width="359" alt="translators_162" src="https://github.com/user-attachments/assets/b37c74e2-fb26-402b-943b-75a0eb6b500a">

**Comment by Dimoks** [comment]
And what does _ = ts.preaccelerate_and_speedtest() actually do?
It seems that no parameters of further requests are changed.
