### ISSUE TITLE
The function ‘youdao’ can only translate the first 50 characters.

### ISSUE THREAD

**Issue by SeamasSun** [UlionTse/translators#19]
In [2]: import translators as ts
In [3]: ts.youdao('If you have requests error, please check whether this service is provided in your country or region.','en','zh')
[09:56:28] UseTimeSeconds(fn: youdao_api): 1.33
Out[3]: '如果你有请求错误,请检查是否t'.

thx.

**Comment by UlionTse** [comment]
@SeamasSun Solved. Please `pip install translators --upgrade` again.

**Comment by SeamasSun** [comment]
Thank you for your help.

**Comment by prigioni** [comment]
> @SeamasSun Solved. Please `pip install translators --upgrade` again.

请问哪个版本有道可以翻译不受字符限制
