### ISSUE TITLE
多个接口失效

### ISSUE THREAD

**Issue by SeamasSun** [UlionTse/translators#20]
有道只翻译前50个字符，腾讯，DeepL接口报错，麻烦作者修改：）

**Comment by UlionTse** [comment]
@SeamasSun Solved it.

**Comment by SeamasSun** [comment]
OK，thx

**Comment by zhu1090093659** [comment]
> @SeamasSun Solved it.

deepl的接口又失效了

**Comment by UlionTse** [comment]
@zhu1090093659 It is unstable doesn't mean that it fails. :)

**Comment by UlionTse** [comment]
@zhu1090093659 Please try v4.7.2
