### ISSUE TITLE
Deepl not working for me((

### ISSUE THREAD

**Issue by xitex** [UlionTse/translators#21]
line 4, in <module>
    var = ts.deepl('Hello', 'en', 'ru' )
line 66, in wrapper
    r = func(*args, **kwargs)
line 852, in deepl_api
    ss, sentences = self.split_sentences(ss, query_text, from_language, to_language, proxies)
line 794, in split_sentences
    r.raise_for_status()
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 415 Client Error: Unsupported Media Type for url: https://www2.deepl.com/jsonrpc

**Comment by UlionTse** [comment]
@xitex Solved it, please download v4.7.2
