### ISSUE TITLE
Baidu api returns partial result

### ISSUE THREAD

**Issue by mozbugbox** [UlionTse/translators#22]
For multi-line content, the baidu translator returns only first line in simple result. The actual simple result should be:
```
        simple_data = '\n'.join([x['prefixWrap'] * '\n' + x['dst'] for x in data['trans_result']['data']])
```

Great job!

**Comment by mozbugbox** [comment]
And for youdao, the simple_data should be joined by newline(`"\n"`), not empty space(`""`).

**Comment by UlionTse** [comment]
@mozbugbox Good issues. Please upgrade v4.7.3 to use it.
