### ISSUE TITLE
DeepL API不工作

### ISSUE THREAD

**Issue by ymilv** [UlionTse/translators#28]
pypi安装的4.7.9版本
deepl报错，请求返回400，查了一下请求
在PostMan里发送：
`{
    "jsonrpc": "2.0",
    "method": "LMT_handle_jobs",
    "params": {
        "jobs": [
            {
                "kind": "default",
                "raw_en_sentence": "MIT License",
                "raw_en_context_before": [],
                "raw_en_context_after": [],
                "preferred_num_beams": 4
            }
        ],
        "lang": {
            "user_preferred_langs": [
                "JA",
                "ZH",
                "EN"
            ],
            "source_lang_computed": "EN",
            "target_lang": "ZH"
        },
        "priority": 1,
        "commonJobParams": {},
        "timestamp": 1606466429798
    },
    "id": 65830012
}`
是可以工作的
但在split_sentences()中请求时返回：
`{
    "jsonrpc": "2.0",
    "error": {
        "code": 1042911,
        "message": "Too many requests."
    }
}`

**Comment by UlionTse** [comment]
@ymilv You would upgrade `translators` to V4.7.11, try again. But in China, `deepl` is usually unstable.
