### ISSUE TITLE
Google translate is not working

### ISSUE THREAD

**Issue by bredpittt** [UlionTse/translators#29]
Hello, 

I have a problem with Google translate:

```
>>> import translators
Using Russia server backend.
>>> translators.google('Привет', from_language='ru', to_language='en')

```

After debugging I think the problem is here https://github.com/UlionTse/translators/blob/master/translators/apis.py#L217

Can you check please?

**Comment by EstebanPiacentino** [comment]
Just saw the same thing. +1!

**Comment by opennota** [comment]
Yep. They've changed the way translate.google.com interacts with their backend server.

**Comment by xitex** [comment]
same problem((

**Comment by zhuchenxi** [comment]
how to solve this problem?

**Comment by UlionTse** [comment]
@bredpittt @EstebanPiacentino @xitex @zhuchenxi Long time wait, sorry. Please upgrade it to v4.7.12

**Comment by xitex** [comment]
Hi man! Thank You!!! through the function
translated = ts.translate_html(clean_article, to_language = 'ru') ok
through google i have got an errors

translated = ts.google(str(clean_article), to_language = 'ru')
  File "\venv\lib\site-packages\translators\apis.py", line 341, in
google_api
    data = execjs.get().eval(json_data[0][2])
  File "\venv\lib\site-packages\execjs\_abstract_runtime.py", line 25, in
eval
    return self.compile('', cwd=cwd).eval(source)
  File "\venv\lib\site-packages\execjs\_abstract_runtime_context.py", line
27, in eval
    return self._eval(source)
  File "\venv\lib\site-packages\execjs\_external_runtime.py", line 72, in
_eval
    if not source.strip():
AttributeError: 'NoneType' object has no attribute 'strip'

пн, 28 дек. 2020 г. в 07:23, UlionTse <notifications@github.com>:

**Comment by UlionTse** [comment]
@xitex Maybe [pyexecjs](https://github.com/doloopwhile/PyExecJS/blob/e300f0a8120c0b7b70eed0758c3c85a9bd1a7b9f/execjs/_external_runtime.py#L71)'s bug of parsing json. I will try to solve it.

**Comment by UlionTse** [comment]
@xitex Please upgrade it to `v4.7.13`
