### ISSUE TITLE
Yandex translator broken

### ISSUE THREAD

**Issue by slav0nic** [UlionTse/translators#31]
test.py did't work correct

**Comment by rubencabrera** [comment]
When I hit the same issue:
```
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 10 (char 9)
```

Looked at the response, which has a 200 code but the json content might be more telling:

```
{"type": blocked}
```

Looking at Yandex docs, it says:

```
To access all Yandex.Translate API v1.5 methods, you need an key. Starting May 27, 2020, free API keys aren't issued.
```

Translators library is not using v1.5, but v1, though that might not make much difference if Yandex is encouraging people to use their cloud translate services instead.

**Comment by UlionTse** [comment]
@rubencabrera Please upgrade v5.0.0, I have fixed it.

**Comment by rubencabrera** [comment]
Yes, I can confirm it works for me installing 5.0.0. Thanks for the quick fix!
