### ISSUE TITLE
inconsistent results

### ISSUE THREAD

**Issue by bjquinniii** [UlionTse/translators#33]
I think I understand the intent of the project, so I ran the following code to do a simple English => Portuguese translation for each service using the following code:

```
# encoding: utf-8

import sys
import translators as ts


en_text = 'this is a test'

try:
	print('google:', ts.google(en_text, from_language='en', to_language='pt'))
except:
	print('google:', sys.exc_info()[0])
try:
	print('yandex:', ts.yandex(en_text, from_language='en', to_language='pt'))
except:
	print('yandex:', sys.exc_info()[0])
try:
	print('bing:', ts.bing(en_text, from_language='en', to_language='pt'))
except:
	print('bing:', sys.exc_info()[0])
try:
	print('sogou:', ts.sogou(en_text, from_language='en', to_language='pt'))
except:
	print('sogou:', sys.exc_info()[0])
try:
	print('baidu:', ts.baidu(en_text, from_language='en', to_language='pt'))
except:
	print('baidu:', sys.exc_info()[0])
try:
	print('tencent:', ts.tencent(en_text, from_language='en', to_language='pt'))
except:
	print('tencent:', sys.exc_info()[0])
try:
	print('youdao:', ts.youdao(en_text, from_language='en', to_language='pt'))
except:
	print('youdao:', sys.exc_info()[0])
try:
	print('alibaba:', ts.alibaba(en_text, from_language='en', to_language='pt'))
except:
	print('alibaba:', sys.exc_info()[0])
try:
	print('deeple:', ts.deepl(en_text, from_language='en', to_language='pt'))
except:
	print('deeple:', sys.exc_info()[0])
```

The results usually came out as:
Using United States server backend.
google: isto é um teste
yandex: <class 'translators.apis.TranslatorError'>
bing: Isso é um teste
sogou: Isso é um teste
baidu: <class 'execjs._exceptions.ProgramError'>
tencent: Istoéumteste.
[02:38:12] language_map:
NoneType: None
youdao: <class 'translators.apis.TranslatorError'>
alibaba: Este é um teste
deeple: este é um teste

It would appear that yandex, baidu and youdao are broken. They all consistently gave the errors shown though the calls are identical, unless of course I'm doing something wrong. Also, it's the youdao call that is responsible for the language_map piece (I commented out all of the other calls and ran it again to make sure).

It's not showing up now, but the alibaba one was complaining about "too many requests" the first few times I ran the code. I had only made a few calls at that point. Are you aggregating the calls?

Last odd bit is that tencent appears to be stripping out the spaces.

Before I wrapped the calls in try/except blocks, I was getting some longer error readouts that seemed to indicate that you're using the requests package under the hood somewhere? Does that mean that requests style proxy parameters could be used?

**Comment by UlionTse** [comment]
@bjquinniii Thanks for your response.
