### ISSUE TITLE
Need help please !

### ISSUE THREAD

**Issue by NatHsn26** [UlionTse/translators#34]
Hello!
Im creating a personal script used to give me all traduction of all possibility of a word.
So eat : eat eta aet ate tea tae 
At first i would know how to put in a variable the language from where the traduction come, cant find how to do write even with help setting (i put code on end)
Iam gonna try edit this script but need study before ,i dont code since many years , i got help to do that. Will edit to put a loop in the last print fonction which must say me all the possible traduction of each word variant ,but only if the result changed.
You know,what im doing now is very slow and check all language for each word assembly should take an hour really lol. 
Do you have an advice to make it faster ? For example a loop in the loop or something like that.Im not really finding idea yet now which can make faster . I can remember one other things when i followed the the lesson ,years ago,its made to execute many things at same for if its to slow. Unfortunately i cant find this again, im not sure it was for python i learned many language but i hope so,if i am right and you have this in your memory ill take it ! Id really need a fast logiciel to dont waste time and study more&better.
If you no have time to share me a good helper idea 💡 there is no problem im can ask away i know its not rlly the spot for ahah but im trying by the way .just need the lang information !
Here the actually code :)

import translators as ts
from translators import apis
def permut(mot):
	if not mot:
		yield ""
		return
	# if
 
	for i in range(len(mot)):
		for x in permut(mot[:i] + mot[i+1:]):
			yield mot[i] + x
	# for
# permut()
for x in permut("abced"):
    print(x+" : "+ts.google(x)+" ("+NEED CODE HERE+")")

okok see u soon

**Comment by UlionTse** [comment]
@NatHsn26

**Comment by NatHsn26** [comment]
Thats really better than mine, thanks you im gonna take it .
But not exactly what i want , excuse my English is bad// i would the script to translate from detect to french, but type only the result if in and out .lower() is different, and mostly important , i would it to say me the language it come from ,thats what i cant find how to do, the deepl method doesn’t work
Eat : manger (english) 

by the way cant translate with deepl i can give more info if you want idk if the bug come from my device or is a dev bug but google shall be suffisant for me)

**Comment by NatHsn26** [comment]
Nice for the multiprocessing im gonna learn on this , i was searching about threading . I hope that will make all that faster. Ty)
