### ISSUE TITLE
‘NoneType’ object is not iterable

### ISSUE THREAD

**Issue by NatHsn26** [UlionTse/translators#36]
I have this error in some case,
For example if i give one letter,all the letter will work normally , its will gimme translate but if i give the "a" letter i got the following error.
Or someword give me the same error during the search generally during the translate of 100/200th word sometime less sometime more .

type word here :A
there is as much possibility: 1
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-e4ea6434af64> in <module>
     28     list2.append(1)
     29     list3.append(1)
---> 30     list3[P]=trad(str(list1[P]))
     31 
     32     vo=(list3[P]).lower()

<ipython-input-2-e4ea6434af64> in trad(t)
      7 
      8 def trad(t):
----> 9     u=ts.google(t,to_language='fr')
     10     return u
     11 

/var/mobile/Containers/Data/Application/DE79D566-42C7-4545-B9DE-422DDE1F789C/Library/lib/python3.9/site-packages/translators/apis.py in google_api(self, query_text, from_language, to_language, **kwargs)
    338         time.sleep(sleep_seconds)
    339         self.query_count += 1
--> 340         return data if is_detail_result else ''.join([x[0] for x in data[1][0][0][5]])
    341 
    342 

TypeError: 'NoneType' object is not iterable

**Comment by UlionTse** [comment]
@NatHsn26 The reason for this problem is that the French translation is caused by two results displayed at the same time, which means you can apply `is_detail_result=True` to get the results you want. But the translation result of this kind of word may not be suitable for universal analysis method.

**Comment by NatHsn26** [comment]
I changed it ty,the error disappeared and its usefull.

I think i can be interested in using this.
Im not sure to understand the utility of all this i would help again please .
Take your time please.

In first case iam thinking everytime the last word, in each result of a search,is the detected language source?Maybe you have a trick for me , i would in fact just return when i want it , the input , the translate and only the language detected, any easy way ?
Maybe i should do a function that runs the stringed each result to search in ,all the language initial it finds , and when many is find in it (bc i see there is always at least 2 time the language source in the result)take it as the source . Or easiest way exists maybe as a method or other that give strict information required thanks could be so much better.
And not only easiest,equally more safe because cant be good in all case with my idea.

And the rest seem interesting except there is lot of ‘None’ idk what is it ? Maybe it will be usefull to me in a near future.

For the A letter for example, i have the right to many information with it, 
I am wondering if this is the site proposition for what goes with the input. 
That would find really a lot of utility for me,but google about information isn’t same. They are in this case more complete ofc.
Maybe something to do to ‘extend’ it ,have all google info i mean? Could be interesting for me really.

You see ,my wishes is also to have all the translation usefull of what i give ,but i will be maybe obligated to use other logiciel idk.I finded recently a translator thats give all possible trad and source of a word but would need to pay it **
But i can see for letter Z manyy more things is given to me as many language and many language info thats weird . Maybe its what i am searching for 
Here you can see the few things returned for « A », and Z...

The key of , an air in,the letter ,she got an ,in science , you can play it in,blood group,

and more result probably chinesse
And some things like idk what is it : none;minor;negative;sharp;positive;flat;?;in science;... i would understand all this maybe send me to the code right spot is good idea idontknow if all that is to much complicated 

I just see too after have write you this message thats the word "niche" have a lot of more information than A , but A have a lot important information see here on google trad: 
https://translate.google.fr/?hl=fr&sl=auto&tl=en&text=a&op=translate
Searching so to get all information about something,the source detected,and all language that have a link with exact same word etc you see ..

Type word here :A
there is as much possibility: 1
( 0 / 1 ) A : None, None, en, 0, None, 5, True, 5, "UN", None, （阳性）, None, None, None, None, 2, "UNE", None, （阴性）, None, None, None, None, 1, fr, 2, auto, "A", auto, fr, True, en, A, None, None, <b>A</b> negative, None, the key of <b>A</b>, None, an air in <b>A</b> major, None, an air in <b>A</b> sharp, None, an air in <b>A</b> minor, None, the letter <b>A</b>, None, <b>A</b> positive, None, she got an <b>A</b> in science, None, can you play it in <b>A</b>?, None, an air in <b>A</b> flat, None, blood group <b>A</b>, 10, 11, None, None, 名词, la, None, la, A, lah, 2, True, fr, en, 1, None, None, en, 1
all that mean nothing:  []




type word here :Z
there is as much possibility: 1
( 0 / 1 ) Z : None, None, pl, 0, None, 5, True, 5, None, None, None, None, None, "AVEC", "AVEC", "À", "DE", "With", " AVEC", fr, 1, auto, "Z", auto, fr, True, pl, z, None, None, None, None, 介词, de, None, z, do, od, od czasu, w, za, 3, True, à, None, w, we, na, u, przy, z, 3, True, en, None, jak, na, po, podczas, w, z, 3, True, dans, None, w, u, na, do, po, z, 3, True, de dessus, None, sponad, z wierzchu, znad, z, 3, True, en provenance de, None, z, 3, True, de chez, None, od, z, 3, True, entre, None, między, pomiędzy, wpośród, z, 3, True, avec, None, z, ze, razem, wraz, dzięki czemuś, przy pomocy czegoś, 3, True, fr, pl, 9, None, None, pl, 1
all that mean nothing:  []


If needed to advice me ,i can give my code ,thanks you X
And see you take care

**Comment by UlionTse** [comment]
@NatHsn26 Hi, friend.

**Comment by NatHsn26** [comment]
Hellohello:)

**Comment by UlionTse** [comment]
@NatHsn26 Hi, friend. 
1. Predict which language the word is. You can use `from_language='auto'` to let the translation predict by itself. The second is to use the [langdetect](https://pypi.org/project/langdetect/) open source framework, and then confirm `from_language`. 
2. In fact, the `translators` framework is more suitable for translating sentences and articles, rather than multiple interpretations of a word. If you like it, I recommend you this website [wordnik](https://www.wordnik.com/).

**Comment by NatHsn26** [comment]
Oh okay thats cool for langdetect lib im gonna learn on this thank you:*
yea i am generally doing with natural search but the thing is it can take lot of time i am gonna stay on other way i hope i'll be able to develop something usefull to myself.

Maybe you can light me if you know how langdetect work ,
Can this function be used to help me to say me all language in which the word exist ?

from langdetect import detect_langs
>>> detect_langs("Otec matka syn.")
[sk:0.572770823327, pl:0.292872522702, cs:0.134356653968]

Thats To find out the probabilities for the top languages

**Comment by NatHsn26** [comment]
In fact im more interested in the use to see what phrase i can do with a phrase i think, already find my happiness by this way on googletrad website , but word is usefull too that is impressionnant how word is wellchoose

**Comment by UlionTse** [comment]
@NatHsn26 Hi, friend.
1. Mark a large number of samples in each language and construct a multi-classification model.
2. I understand your demands for perfect expression, but it may not be suitable to be implemented in this translation framework. You think that the translation is imperfect by default, but what the translation gives you is what he thinks is the most perfect translation result. So try [grammarly](https://www.grammarly.com/)!

**Comment by NatHsn26** [comment]
Hey Ulion ! All my excuses for the wait delay i was very bussy dont get enough time for myself. Finally with the « is_Detail_Result=True » it’s good for the moment dont need more, lets see later i just take the abbreviated language in the result and convert it thats working fine 🖐
 Yes you right thats nearby like this with all translator framework there are error and in add of this there are lot of shit on google trad when you use it via website , bc ppl can add what they want in suggest *lol•
 
Maybe i am gonna in the future use a different one i found ,u must buy characters idk how much money that represents that very expensive i think ,ill see but for the moment this one is suffisant to me :) .

By the way i am seeing when isdetailresult is on true , you know in the result nearby at the middle of the string returned with all the info , there are some word which seem to be probably word going with input ,
I seen sometime the syntax give is not good. I mean you have a comma ,then open the quotation mark ,the word is written ; but mark never close ,you have after it an other comma other quotation mark,another word (sometime after the word ,quotation get close but not always if i remember good), maybe its have any report with the other problems you searching a solution for idk.
Im can find you exemple if that can help you np .
I seen that by taking all characters surrounded by «”» , but also sometime, rarely ,the word given as proposition in the middle of the result , isn’t surrounded by quote , only by comma . Is that normal ?

well, i need to trad all permut of a word , so it would be to slow to do by hand, but in the future it will be important for me to search on web dictionary if the word input have any report with the answer proposed if result is none , and some proposition is given.But thats not for the moment i dont know python enough for now to attack this ^^
already add Grammarly bc of ad on YT lol.
Good day !

ps: there are some lang abbreviation i cant be sure which language it is, i suppose you ignore this if it cant be find on internet? 
Oh im just thinking now during writing precedent sentence, i could do a code to trad a word to this lang and search the word on internet after im gonna try this
