### ISSUE TITLE
How many quotas each API support?

### ISSUE THREAD

**Issue by l4zyf9x** [UlionTse/translators#38]
First of all, thanks for your interesting work
I wonder what is the limit of each API?
I already tried to call continuously Bing API under 100 times and got HTTP Response message 429, which means I already reach limit quotas.
Do you have any information about quotas for each API. Glad to see it :D

**Comment by UlionTse** [comment]
@l4zyf9x Hi friend,
I am not sure about `the api` call limit per minute, so you also need to try, try not to call too frequently. Try a random and larger prameter `sleep_seconds`.
