### ISSUE TITLE
can't install package

### ISSUE THREAD

**Issue by adbenitez** [UlionTse/translators#4]
tried to install translators using pip, the module is loaded in the setup.py to get the version, but at this time dependencies aren't installed and the installation crashes.

**Comment by shinalone** [comment]
@adbenitez Sorry, I don't know if you're using the wrong command, but you can try `pip install translators` or `pip install translators==4.0.4`, also `pip install translators==4.0.3`.

**Comment by adbenitez** [comment]
hi, I tried just `pip install translators` also cloning the repo with git and trying `python setup.py install` gives the same issues (under a python3 virtual environment so python command is actually python3)

**Comment by adbenitez** [comment]
I get an error that "can't import execjs", when executing `pip install translators` because you load the module to get `__version__` but you also load the other modules in `__init__.py`

**Comment by shinalone** [comment]
@adbenitez Or you may `pip install pyexecjs` first. 

![translators_06_21_2019](https://user-images.githubusercontent.com/14334826/59896421-12af0a80-941b-11e9-8794-188374bc128e.jpg)

**Comment by adbenitez** [comment]
sure, but the whole point of using pip is that it installs dependencies automatically, so users can just do 
`pip install translators` it should work out of the box, please consider my PR or a similar approach to make this work out of the box.
Regards,
adb

**Comment by UlionTse** [comment]
@adbenitez Thanks, I have fixed it with your advice. Today I will close this issues.
