### ISSUE TITLE
 HTTPError: 400 Client Error: Invalid JSON-RPC request for url: https://www2.deepl.com/jsonrpc

### ISSUE THREAD

**Issue by lonngxiang** [UlionTse/translators#41]

**Comment by UlionTse** [comment]
@lonngxiang 

Hello friend,
I will try to fix it in the next version, thank you for your feedback.

**Comment by lonngxiang** [comment]
> @lonngxiang
> 
> Hello friend,
> I will try to fix it in the next version, thank you for your feedback.

thumbs up

**Comment by lonngxiang** [comment]
> @lonngxiang
> 
> Hello friend,
> I will try to fix it in the next version, thank you for your feedback.

thumbs up

**Comment by cool-delete** [comment]
Is this wrong meaning that URL is wrong?

![image](https://user-images.githubusercontent.com/13638610/120953407-799c6a00-c77f-11eb-8300-3961d046e040.png)
