### ISSUE TITLE
translators.apis.TranslatorError: Unsupported to_language[en]

### ISSUE THREAD

**Issue by me-suzy** [UlionTse/translators#42]
hello, seems to have this bug on my Py script:

**translators.apis.TranslatorError: Unsupported to_language[en]**

The error in that library is that it doesn't translate at all.
It just makes an error on the code and stops the program

**Comment by NatHsn26** [comment]
Hello i just got the same problem,i opened an issue 1/2 month ago and so,he is probably still working on it i was not far to ask him how it is going.Also you can check this conversation its may help you, you can 'active' by yourself the language needed like this while its got a patch;

ts._google.language_map={'en':['fr'],'fr':['en']}

Also i can provide you the full command line to init all the language if you need the totality of its,but not here its a very long command,idk how to post something on this platform so maybe someone can explain me,or i can send by mail

**Comment by me-suzy** [comment]
hello. Send here: me.suzana@gmail.com

**Comment by UlionTse** [comment]
@me-suzy 

Hello friend, this https://github.com/UlionTse/translators/issues/37#issuecomment-822154956

**Comment by me-suzy** [comment]
@UlionTse thanks. This will solve the problem.

https://github.com/UlionTse/translators/issues/37#issuecomment-822154956

**Comment by me-suzy** [comment]
@UlionTse thanks. Maybe the link you gave me above will solve the problem.

@UlionTse  You should write the solution code somewhere.  https://github.com/UlionTse/translators/issues/37#issuecomment-822154956 These are just code images that need to be corrected. People didn't feel like copying that code, they wasted a lot of time.

Also, the error must be solved first. So that the user does not encounter any errors.
