### ISSUE TITLE
baidu trans_result

### ISSUE THREAD

**Issue by sugardove** [UlionTse/translators#43]
--> 26 print(ts.baidu(wyw_text, professional_field='medicine')) # ('common','medicine','electronics','mechanics')
     27 
     28 # property

~\AppData\Roaming\Python\Python36\site-packages\translators\apis.py in baidu_api(self, query_text, from_language, to_language, **kwargs)
    490         time.sleep(sleep_seconds)
    491         self.query_count += 1
--> 492         return data if is_detail_result else '\n'.join([x['dst'] for x in data['trans_result']['data']])
    493 
    494 

KeyError: 'trans_result'

**Comment by UlionTse** [comment]
@sugardove Hello friend,
please provide more detail infomation. 

For me:
![png](https://i.loli.net/2021/06/16/jzHXNvqk2F5be3u.png)
