### ISSUE TITLE
Unsupported language info?

### ISSUE THREAD

**Issue by NatHsn26** [UlionTse/translators#44]
Hey friend,you just put solved on our conversation; you wont be able to make it work as normal ?

**Comment by UlionTse** [comment]
@NatHsn26 Hello friend,
which issue do you discuss? 
There are no more than two reasons for closing an issue. One is that the solution is resolved through external discussions, and there is no discussion for a long time. The other is to solve internally through version iteration, even if it may not be perfect. Obviously, these two are in line, why can't it be closed?

**Comment by NatHsn26** [comment]
Hey, i am talking about the unsuported-language error which make me always have 0 iyem in the labguage_map ,im not a good knower of this apps, as i seen its have been added a solved label i thought i messed something provably.but i understood too with my not so good english that the « at present,there is a solution..[...] « in the early stage<-i understood here as proper translation that its mean its a solution while the things go back to normal acting »but right i understand now with Google translate to help me (lol)that you was probably meaning ‘before use the library,first of all you will need to create the language_map’ but anyway i shared with you a note with the France’s google trad homepage so im curious to know if something is going better in your search? As i am because i need eventually all language,launching a 80k character command line at every launch and i already gave this command to 2 people by mail (idk how to post on this app as they asked me.,)i imagine some people wont take the time to do a script to get this command line if they need lot of language. So yeah anyway what i understood is that you will do what you can for its go back at its normal working way without we have to launch individually each language. Thats why i didn’t understand why it’s closed if in France at least i still naturally no have a map fullfiled

**Comment by UlionTse** [comment]
@NatHsn26 Hello friend,

If you use the updated version[4.7.20], you will find that this problem is indeed solved, but there is indeed a little regret, it is an imperfect solution. 

Look this:wink::
#37
[Sourcecode Link](https://github.com/UlionTse/translators/blob/08aa515dcb9f14744c56a90f5e3af181e6c705a1/translators/apis.py#L366)
[Version Iteration Description](https://github.com/UlionTse/translators/blob/08aa515dcb9f14744c56a90f5e3af181e6c705a1/change_log.txt#L166)

If you think it is necessary to reopen it, there is no problem, I will reopen it. do you think it's okay?

**Comment by NatHsn26** [comment]
Ohh okay nice didn’t know there is a new version, just trying now but weirdly the language map say me is Empty(None) when i use the print function, but i cant use the len() function as it say me object of type 'NoneType' has no len().i think remember i was using the len on this attribute.
Also by the way i am not professional enough to judge of this new code you provided so wouldn’t too have thing to propose if i open again the issue😂.But also i got another error of same kind when i run my script and its that ;
TranslatorError: query_text is not string.

i dont know if i should open a new issue for this i let you say me :)

**Comment by NatHsn26** [comment]
Maybe i get it a better on this solution you gave us but which is imperfect, is it creating a language map with the one im using as to/from ?
