### ISSUE TITLE
Request: allow to set timeout to avoid hangs/freeze

### ISSUE THREAD

**Issue by adbenitez** [UlionTse/translators#47]
seems like the request might hang forever, would be good that a timeout could be passed to the API (and passed down to `requests` lib) or at least that internally the lib use timeouts everywhere in `requests` calls to avoid hanging forever

**Comment by UlionTse** [comment]
@adbenitez OK, I will add it in the next version.

**Comment by UlionTse** [comment]
@adbenitez OK, I will add it in the next version.
