### ISSUE TITLE
429 error.

### ISSUE THREAD

**Issue by HARSHADBHIRUD** [UlionTse/translators#48]
error thrown as bellow:
429 Client Error: Too Many Requests for url: https://www.bing.com/ttranslatev3?isVertical=1&&IG=0138A424292346E684700834F252CCE3&IID=translator.5023.90

need resolution for the same

**Comment by UlionTse** [comment]
@HARSHADBHIRUD Eeeeh... Too Many Requests! So you should set `sleep_seconds` and look at [this](https://github.com/UlionTse/translators#httperror-4xx).
