### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by NatHsn26** [UlionTse/translators#51]
Hi
I may be looking bad or i miss something,i dont see any new information but not any of my code work they all stooped as i said yesterday.
Even this dont work but i dont see any required arguments needed its should go from french to english no ?:

import translators as ts
print(ts.google("bonjour")) 

Ive got an insertion error in most part of case but also if i ask for the language map after its imported, its show me an empty map. I hope you can enlighten me.

**Comment by UlionTse** [comment]
@NatHsn26 Hi,
1. Please provide more **objective** information, **not subjective** information. For example, translators version, Python version, operating environment, whether the country you are in provides relevant translation services, etc. 
2. Why do you ignore the error message? Like yesterday's error, you didn't type in a string format, etc. 
3. For me:
![ts_french](https://user-images.githubusercontent.com/14334826/133701882-5a57e57e-b545-4c65-a491-057eb5dda4ca.png)

**Comment by TheItsNameless** [comment]
I have the same Issue:

```
>>> import translators as ts
Using Germany server backend.
>>> ts._google.language_map
>>> ts.google('Bonjour')
C:\Users\[username]\AppData\Local\Programs\Python\Python39\lib\site-packages\translators\apis.py:117: UserWarning: Did not get a complete language map. And do not use `from_language="auto"`.
  warnings.warn('Did not get a complete language map. And do not use `from_language="auto"`.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\[username]\AppData\Local\Programs\Python\Python39\lib\site-packages\translators\apis.py", line 380, in google_api
    self.language_map = self.make_temp_language_map(from_language, to_language)
  File "C:\Users\[username]\AppData\Local\Programs\Python\Python39\lib\site-packages\translators\apis.py", line 118, in make_temp_language_map
    assert from_language != 'auto' and to_language != 'auto' and from_language != to_language
AssertionError
>>>
```

Could it have something to do with the server backend which was selected at start?
But maybe it could be the python version i am using? I use 3.9.6.

**Comment by UlionTse** [comment]
@TheItsNameless Hi,
1. The lack of access to `language_map` is a problem, but it is not the cause of the error. When a `language_map` cannot be obtained, a new one is created temporarily. In this case, you need to specify `from_language`  and it cannot be "auto".
2. I'm very curious to know why none of you read the error messages and warnings carefully.
3. Please continue to enter:
`ts.google('Bonjour', from_language='fr', to_language='en')`

**Comment by NatHsn26** [comment]
Hey, ahh yes right i read that its cant be auto in my case too but i didn't minded why lol.?no idea why i didn't ask you.The cited code about the error happening was meaning nothing for me that may have disturb me. 

Also i will say you the information i should have said you before may be usefull about the language map bug; i hope so,i use to be always on 'auto' and thats what interest me. 
Maybe that i dont have the last python version have a role in this bug(3.9.2) i am running on IOS and i am in France .

Also the first subject closed that you asked me,it was always working like this,i dont think i edited anything, was just giving a var with a string content not using quote directly. I think it stopped work when i updated the library month ago or arround this time i am not sure
