### ISSUE TITLE
UserWarning info?

### ISSUE THREAD

**Issue by ObedH26** [UlionTse/translators#53]
Hey

When i run something i got notified by this

Using France server backend.
/var/mobile/Containers/Data/Application/891949C4-9BE2-44EF-82B1-76377D19A064/Library/lib/python3.9/site-packages/translators/apis.py:117: UserWarning: Did not get a complete language map. And do not use `from_language="auto"`.
  warnings.warn('Did not get a complete language map. And do not use `from_language="auto"`.')

I am wondering if you are working to get this to work same way as before if you get me ? 
Nathan

**Comment by UlionTse** [comment]
@NatHsn26 
You kept saying you couldn't get the `language_map`, so I made a fix. But please provide relevant evidence in the same picture, or I will Sue you for defamation. Smile to cry😂. 
If possible, please copy the source code of [view-source:https://translate.google.com](https://translate.google.com) and save it as a file and send it to my [mailbox](shinalone@outlook.com), so as to test whether the same website displays different resources in different countries and regions.

**Comment by NatHsn26** [comment]
Ahah sorry if i did something wrong, im not sure to get what you mean when you say provide relevant evidence in the same picture 😅
But i make you here a video i hope github launch it correctly, and ill send you the source page code asap just need to borrow a computer as my power cable died last week =)
Also i can get the language map by imputing and i have a long command to do it,but its embarrassing to me to dont be able to use autodetect to be honest 
https://user-images.githubusercontent.com/80646073/143866271-c48d28fc-2481-42dd-9d9b-cd57091d718d.MOV

**Comment by UlionTse** [comment]
@NatHsn26 I saw your video. You have to call the translation **at least once** before the class instance is assigned.

**Comment by NatHsn26** [comment]
Oh okay iam terribly sorry,i was probably missing the from_language when i noticed this lol.
I think so it is normal the languagemap is set on "None" after a successful translate,i think you said time ago it was a provisional solution 
Hope you guys will get this to detect language:H
Let me now if you still want the source code

**Comment by UlionTse** [comment]
Done.

**Comment by ObedH26** [comment]
Thanks pro ill check that
