### ISSUE TITLE
Feature request: add LibreTranslate support

### ISSUE THREAD

**Issue by hendursaga** [UlionTse/translators#54]
[LibreTranslate](https://libretranslate.com) is an API wrapping [ArgosTranslate](https://github.com/argosopentech/argos-translate), a 100% libre machine translation library. It would be great if it were supported.

**Comment by UlionTse** [comment]
@hendursaga OK. Let me find out first.

**Comment by UlionTse** [comment]
@hendursaga [LibreTranslate ](https://github.com/LibreTranslate/LibreTranslate#mirrors) is not free!

**Comment by hendursaga** [comment]
@UlionTse You are correct in saying the main LibreTranslate instance is not gratis (aka not free as in free beer), but it's free-as-in-freedom and some of the other instances listed there do not charge access to an API key. I found it very trivial to setup my own instance on my Linux machine.

**Comment by UlionTse** [comment]
@hendursaga Try `pip install translators==4.9.6` and `translators.argos()`'s parameter `set_host_url`.
