### ISSUE TITLE
Tencent returns translation with no whitespace

### ISSUE THREAD

**Issue by ben-pike** [UlionTse/translators#55]
Tencent seems to be returning the correct translation as a string, but without whitespace.

    import translators as ts

    def tencent_translate(sentence):  
           translation = ts.tencent(sentence, from_language='en', to_language='es') 
           return translation

`tencent_translate('Hi how are you')` returns 'Hola,¿cómoestás?' (as opposed to 'Hola, ¿cómo estás?' )

I am using version 4.9.6 of the package in a Jupyter notebook with Python 3.8.8

**Comment by UlionTse** [comment]
@ben-pike Check `is_detail_result` as usual. But you can see my picture:
![截屏2021-11-29 上午11 05 28](https://user-images.githubusercontent.com/14334826/143802378-b535cbeb-dd1d-4794-b98e-6915837b396b.png)
