### ISSUE TITLE
translators in PYW file is ignored or the program is CTD

### ISSUE THREAD

**Issue by kucingkembar** [UlionTse/translators#58]
hi, sorry for my bad English, i have this code in a pyw file:
```
import subprocess
subprocess.call("pip install translators --upgrade")
import translators as ts

import sys
if 'translators' not in sys.modules:
	print("not loaded")
else:
	print("loaded")
input("Press Enter to continue...")
```
when I open via idle 3.9, then run module (F5), the program runs fine
```
Using Singapore server backend.
loaded
Press Enter to continue...
```
but when I open the PYW file, the program is crash to desktop when it tried to import translators,
then I put the import Tkinter GUI button, when I press the button the "msgbox" of "loaded or not loaded" do not appear,
when I tried again using idle 3.9, then run module (F5), the program run fine,

I don't know what happens, can someone help me, please!!

additional info:
I using windows 11
python 3.9 (because some packages do not support 3.10)

**Comment by kucingkembar** [comment]
thank you for the reply, when renamed to py file, the result is normal/working,

sorry for the problem,
what problem caused this?

if I provide the py file instead pyw file to the client, I think it is not professional

**Comment by UlionTse** [comment]
@kucingkembar I think pyw files do not crash, but execute quickly without output, that's all.

**Comment by kucingkembar** [comment]
thank you again for the reply,
so what is the solution?

just for info, when the program work, an exe/cmd appear with red square icon, I forget the name, 
but when not work, the exe do not appear

**Comment by UlionTse** [comment]
@kucingkembar This problem has little to do with the library, and I don't know much about the problem you mentioned.
