### ISSUE TITLE
Translator messes up formatting of channel and user mentions on Discord

### ISSUE THREAD

**Issue by IveMalfunctioned** [UlionTse/translators#59]
So I use this library as part of my Discord bot and the translator is messing up the formatting of channel and user mentions. The clickable user and channel links are formatted in raw text as <#ID> for channels and <@ID> for users. Translating "This is a test <#899101975264776194> general chat" with Google translate on the website works fine but using translators messes up the formatting of it in all 7 languages (English, Spanish, Portuguese, French, Filipino, German, & Italian) the outcome in Spanish is "Esta es una prueba <# 899101975264776194> Chat General". As you can see in puts a random space in there for whatever reason which breaks the link. I don't know if this is a problem that can be fixed but it doesn't break it on the site so maybe it's something with the library

**Comment by UlionTse** [comment]
@IveMalfunctioned About google, merge it into #35

**Comment by IveMalfunctioned** [comment]
What am I supposed to do with `help(ts.translate_html)`
