### ISSUE TITLE
failed to eatablish a connection

### ISSUE THREAD

**Issue by BOSCH1213** [UlionTse/translators#6]
ConnectionError: HTTPConnectionPool(host='fanyi.youdao.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014A781D8D88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by UlionTse** [comment]
@BOSCH1213 Connect the Internet before do it.
