### ISSUE TITLE
`translators` doesn't work with Heroku

### ISSUE THREAD

**Issue by Pysics** [UlionTse/translators#60]
I get this error:
```
 Traceback (most recent call last):
   File "<string>", line 1, in <module>
   File "/tmp/pip-req-build-ritdm4zu/setup.py", line 14, in <module>
     VERSION = __import__(PACKAGE).__version__
   File "/tmp/pip-req-build-ritdm4zu/translators/__init__.py", line 4, in <module>
     from translators.apis import alibaba, argos, baidu, bing, caiyun, deepl, google, iciba, iflytek, sogou, tencent, yandex, youdao
   File "/tmp/pip-req-build-ritdm4zu/translators/apis.py", line 50, in <module>
     import pathos.multiprocessing
 ModuleNotFoundError: No module named 'pathos'
```

This is in my `requirements.txt`:
```
git+https://github.com/uliontse/translators
```

**Comment by UlionTse** [comment]
@Pysics You can directly `pip install --upgrade translators`. Otherwise, like you, you have to install dependency packages, such as `pathos` and so on.

**Comment by Pysics** [comment]
@UlionTse Why doesn't `pip install git+https://github.com/uliontse/translators` work?

**Comment by Pysics** [comment]
> @Pysics `pip install` + compressed package file, such as `whl file`, not dir source file. for dir source file, [attention readme](https://github.com/UlionTse/translators#from-source).

So, what exactly should I put after `pip install`?

**Comment by UlionTse** [comment]
@Pysics `pip install --upgrade translators` or `pip install --upgrade translators-5.0.1-py3-none-any.whl`

**Comment by Pysics** [comment]
@UlionTse This is in my `requirements.txt` file. I also want to install this module from source, but Heroku runs `pip install` at every line. The usual way to do this is `git+https://GitHub.com/user/repo`. How can I do it here?

**Comment by UlionTse** [comment]
@Pysics Why can't you see [this readme](https://github.com/UlionTse/translators#from-source)?

**Comment by Pysics** [comment]
> @Pysics Why can't you see [this readme](https://github.com/UlionTse/translators#from-source)?

But how can I do this on Heroku?

**Comment by UlionTse** [comment]
@Pysics Found through #61  that your python version 3.10 is too high (currently support 3.9). Lower your python version and pip install it.

**Comment by Pysics** [comment]
@UlionTse Is it possible for you to upgrade to Python 3.10?

**Comment by Pysics** [comment]
Thank you!
