### ISSUE TITLE
Is there a way to get a list of languages for a given service?

### ISSUE THREAD

**Issue by Pysics** [UlionTse/translators#62]
@UlionTse Is there a way to get a list of languages for a given service?
For example, I want to get the list of languages for Google. Can I just do this:
```python
print(ts.google.languages)
>>> {"en": "English"...}
```

**Comment by UlionTse** [comment]
@Pysics `ts._google.language_map`, detail to `readme.md`.

**Comment by Pysics** [comment]
@UlionTse But does that return full language names, like `English`?

**Comment by UlionTse** [comment]
@Pysics That's why there is a big language table on the readme. :joy:

**Comment by Pysics** [comment]
@UlionTse I want to access the language names programmatically, but this is not supported.

**Comment by Pysics** [comment]
@UlionTse Is this possible?

**Comment by UlionTse** [comment]
@Pysics The methods provided by each translation service are different, some are obtained through html parsing, and some are obtained from the specified js page. And the format is not uniform, so if you want to get all of them, you can study the source code `get_language_map` code block and try to get it.

**Comment by Pysics** [comment]
Okay, thanks!
