### ISSUE TITLE
IndexError: list index out of range still wtih v5.0.2

### ISSUE THREAD

**Issue by vlasvlasvlas** [UlionTse/translators#64]
got this error while executing in a list of strings:

![imagen](https://user-images.githubusercontent.com/4071796/162053303-7ad9be58-b707-4c2c-bf3b-21b7b72f6ef4.png)

"IndexError: list index out of range"

![imagen](https://user-images.githubusercontent.com/4071796/162050364-422abf36-329e-4524-a975-965eb0af2ef2.png)

**Comment by vlasvlasvlas** [comment]
resolved, my bad :)

**Comment by vlasvlasvlas** [comment]
Just added a counter, to see when this happens, 
after row 180, it just breask with list index out of range:
![imagen](https://user-images.githubusercontent.com/4071796/162057553-cfe8e381-d789-49bd-b7b6-0a468a9baaaf.png)

**Comment by UlionTse** [comment]
@vlasvlasvlas Debug with `isinstance(row['response1'], str)` and `ts.google(texto, is_detail_result=True)`.
