### ISSUE TITLE
iflytek and tencent don't work

### ISSUE THREAD

**Issue by westernoon** [UlionTse/translators#65]
讯飞和腾讯用不了，你看能修改吗？

**Comment by UlionTse** [comment]
@westernoon Please provide more information, such as error information and runtime environment .  About `iflytek()`, you can read [this](https://github.com/UlionTse/translators/blob/63f42465a41059e6cddc57e8ff8d47d5641fea6a/change_log.txt#L236).

**Comment by westernoon** [comment]
Tencent dose work well(I just made a mistake).But iflytek give this error:

### Traceback (most recent call last):
  File "C:\Users\xxx\test.py", line 8, in <module>
    print(ts.iflytek('おはよ',from_language='ja',to_language='zh'))
  File "C:\Users\xxx\Lib\site-packages\translators\apis.py", line 1566, in iflytek_api
    r.raise_for_status()
  File "C:\Users\xxx\Lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://saas.xfyun.cn/ai-application/trans/its

env:
python 3.8.8
translators==5.1.1
PyExecJS==1.5.1
requests==2.27.1
lxml==4.8.0
pathos==0.2.8
loguru==0.6.0

**Comment by UlionTse** [comment]
@westernoon Done.
