### ISSUE TITLE
Google --- 'NoneType' object is not iterable 

### ISSUE THREAD

**Issue by RedHitMark** [UlionTse/translators#69]
`
import translators as ts
`
`
print(ts.google('half', to_language='fr', sleep_seconds=1))
`

Output:
Traceback (most recent call last):
    print(ts.google('half', to_language='fr', sleep_seconds=1))
  File "*********\venv\lib\site-packages\translators\apis.py", line 424, in google_api
    return data if is_detail_result else ' '.join([x[0] for x in data[1][0][0][5]])
TypeError: 'NoneType' object is not iterable

**Comment by UlionTse** [comment]
@RedHitMark Good find. French is special and generates two side-by-side results, so one way is that you can use `is_detail_result=True` to fix it temporarily, and the other is to wait for my fix, which should also be quick.

**Comment by UlionTse** [comment]
@RedHitMark It Fixed, please `pip install --upgrade translators`.
