### ISSUE TITLE
在apis.py下TranslatorSeverRegion这个类需要加上代理

### ISSUE THREAD

**Issue by yuzhiyizhan** [UlionTse/translators#70]
如题:
apis.py下的TranslatorSeverRegion也需要加入代理，我目前临时修改源码来保证不出错

class TranslatorSeverRegion:
    @property
    def request_server_region_info(self):
        proxies = {
            'http': 'http://127.0.0.1:7890',
            'https': 'http://127.0.0.1:7890',
        }
        # https://geolocation.onetrust.com/cookieconsentpub/v1/geo/location
        try:
            ip_address = requests.get('https://httpbin.org/ip',proxies=proxies).json()['origin']
            try:
                data = requests.get(f'http://ip-api.com/json/{ip_address}', timeout=10,proxies=proxies).json()  # http # limit 45/min.
                country = data.get("country")
                if not country:
                    raise TranslatorError('Unknown country or region.')
                sys.stderr.write(f'Using {country} server backend.\n')
                return data
            except requests.exceptions.Timeout:
                data = requests.post(
                    url='https://ip.taobao.com/outGetIpInfo',
                    data={'ip': ip_address, 'accessKey': 'alibaba-inc'}
                ).json().get('data')
                data.update({'countryCode': data.get('country_id')})
                return data

        except requests.exceptions.ConnectionError:
            raise TranslatorError('Unable to connect the Internet.\n')
        except:
            warnings.warn('Unable to find server backend.\n')
            country = input('Please input your server region need to visit:\neg: [England, China, ...]\n')
            sys.stderr.write(f'Using {country} server backend.\n')
            return {'country': country, 'countryCode': 'CN' if country == 'China' else 'EN'}

**Comment by UlionTse** [comment]
@yuzhiyizhan Since it only runs when the library is loaded for the first time and has little impact on the subsequent translation process, and adding proxies is not particularly convenient, I think it is unnecessary. Thanks.
