### ISSUE TITLE
bing translate ---  requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url

### ISSUE THREAD

**Issue by spotted-deer** [UlionTse/translators#76]
error report details :
`zh_cn = translators.bing(description_value, from_language='en', to_language='zh-CN')
  File "F:\Anaconda3\envs\python37\lib\site-packages\translators\apis.py", line 967, in bing_api
    r.raise_for_status()
  File "F:\Anaconda3\envs\python37\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://cn.bing.com/ttranslatev3?isVertical=1&&IG=2714881FCAE441A294CA0DFD71DBC613&IID=translator.5023.99`

**Comment by UlionTse** [comment]
@spotted-deer Such a clear error！https://github.com/UlionTse/translators#httperror-4xx
