### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by muhammedaksam** [UlionTse/translators#77]
I am trying to translate from English to Turkish. I think this happens when there is a gendered translation.

`File "C:\Users\xxx\AppData\Roaming\Python\Python310\site-packages\translators\apis.py", line 427, in google_api return data if is_detail_result else ' '.join([x[0] for x in (data[1][0][0][5] or data[1][0])])`

**Comment by UlionTse** [comment]
@muhammedaksam Please provide more information, such as runtime environment, package version, and simple test performance.

**Comment by muhammedaksam** [comment]
> @muhammedaksam Please provide more information, such as runtime environment, package version, and simple test performance.

- Python Version: 3.10.0
- OS: Windows 11
- App version: 5.3.1

I don't know what is simple test performance. How can I do it?

**Comment by UlionTse** [comment]
@muhammedaksam For example, `print(ts.google('hello', 'en', 'ar'))`, then raise a error, including all error message.

**Comment by muhammedaksam** [comment]
I can't raise same error that occured when I create this issue. But I think that was about my input.

![ss2022-07-11 200733](https://user-images.githubusercontent.com/27314049/178362337-fa7ce71c-87e2-4060-bc7a-9fc3969b0cf1.png)
