### ISSUE TITLE
Make pathos optional dependency

### ISSUE THREAD

**Issue by mercuree** [UlionTse/translators#82]
Pathos is used for translate_html function only, but it requires bunch of own dependencies:
- pathos [required: >=0.2.9, installed: 0.2.9]
    - dill [required: >=0.3.5.1, installed: 0.3.5.1]
    - multiprocess [required: >=0.70.13, installed: 0.70.13]
      - dill [required: >=0.3.5.1, installed: 0.3.5.1]
    - pox [required: >=0.3.1, installed: 0.3.1]
    - ppft [required: >=1.7.6.5, installed: 1.7.6.5]
      - six [required: >=1.7.3, installed: 1.16.0]
 
Because pathos module is imported at the beginning of apis.py, it will break a whole code if I try to remove pathos and its deps.

**Comment by UlionTse** [comment]
@mercuree It Has little effect. If you think some modules have been updated, you can restore the updated modules after downloading.

**Comment by mozbugbox** [comment]
What's the difference between the `pathos.multiprocessing.processPool.map` and the builtin `concurrent.futures.Executor.map`?
