### ISSUE TITLE
parameter problem

### ISSUE THREAD

**Issue by JokersZ** [UlionTse/translators#85]
Hi,firend
I have a small question,Maybe I don't know much about Python.therefore,I may overlook a lot of details
I want to reduce the number of  translate requests  ,
So, I hope the parameter 'query_text' to be of type : Union[str, List[str]].
But now I can only call methods inside a loop

**Comment by UlionTse** [comment]
@JokersZ Hi friend！
You can concatenate multiple short sentences into a single paragraph using newline characters `\n` for translation at once, but the total number of words to be concatenated should not exceed the load of the translation service.
Related Issues #15 #67
