### ISSUE TITLE
The number of responses differs for each execution.

### ISSUE THREAD

**Issue by syuya-tanaka** [UlionTse/translators#87]
Hello!
It's a nice library. I'm letting you use it.

I have a question.

I'm threading API requests for this library,
There's going to be problems.

In the local environment, the number of responses returned and the time it takes vary greatly each time, and even if there are few responses, about 200 are not enough every time.

But when I run it on EC2, the request and response numbers are perfect every time.
The time is about 1/3 compared to local.

I want to clarify what makes this difference.
I know you're busy, but I want you to tell me.

**Comment by UlionTse** [comment]
@syuya-tanaka Hello friend,
If the code is the same, the difference may come from the performance of the EC2 itself and the feedback of the translation service corresponding to the address of the EC2.

**Comment by syuya-tanaka** [comment]
Thank you for your reply!

The code is the same and the EC2 instance type I'm using is t2.micro.
In the local environment, the CPU is Intel Core i5.

I confirmed that the CPU of t2.micro has better performance.

I understand that it may be due to the difference between the performance of EC2 itself and the local performance,
I don't understand the difference due to the feedback of the translation service corresponding to the EC2 address.

I don't quite understand this part, but if you have time, please let me know. 
Do you have any reference material?


supplement
It may be completely unrelated, but the only translation service I use is google.

**Comment by syuya-tanaka** [comment]
@UlionTse 
In this case, can I understand that "merchants" in your reply is Google Translate?

**Comment by UlionTse** [comment]
@UlionTse Yes.

**Comment by syuya-tanaka** [comment]
@UlionTse 
Thanks to you, I was able to know what I didn't know.
I really appreciate it.
Thank you very much for your clear explanation.

**Comment by UlionTse** [comment]
@syuya-tanaka :wink:
