### ISSUE TITLE
How to Translate Very Large Book using translators?

### ISSUE THREAD

**Issue by mobassir11** [UlionTse/translators#88]
i have a very large english book that i want to translate using your library, google translator api call has small limit,it will block me after few api calls but as i have a large book,the google translator api is no longer helpful for me. is this library letting us translate very large books using some proxy or something? the sleep tactic is also not much helpful for me,,if i use sleep then the blocking will still occur after several api calls,i want no blocking to interrupt my translation process maybe using some proxy or something? is there any possible way to translate large book using this library?

**Comment by hubred-rev** [comment]
Youdao Translate support unlimited amount.

**Comment by mobassir11** [comment]
@hubred-rev 

sadly youdao doesn't support bengali.
bangla is supported only by,
google,yandex,bing and sogou according to this chart -> https://github.com/UlionTse/translators#support-language

i wish there was a way to translate unlimitedly for bangla. i tried https://ai.facebook.com/research/no-language-left-behind/ for bangla. it works fine but not best (makes many mistakes during translation)

**Comment by UlionTse** [comment]
@mobassir11 Hello friend,
It is necessary to divide large articles into paragraphs that can be translated at once, then translate multiple paragraphs through multiple processes, and then stitch them back together.

**Comment by mobassir11** [comment]
@UlionTse i tried this https://pypi.org/project/pandarallel/ but after 7-8% processing i face httperror. using your library we can't work on large document i.e "large book" but for small documents it's a good library, thank you.

**Comment by UlionTse** [comment]
@mobassir11 
After all, it is a free service provided by the merchant, and the essence of fast and abundant access is not a technical problem, but must be blocked. Don't be greedy. Hahahaha
