### ISSUE TITLE
google translation is no longer supported

### ISSUE THREAD

**Issue by Remon128** [UlionTse/translators#89]
The google translation is not working anymore and crashes with this message 
404 Client Error: Not Found for url: https://translate.google.cn/_/TranslateWebserverUi/data/batchexecute

**Comment by UlionTse** [comment]
@Remon128 Hello friend,
Because `Google Translate` just stopped its translation service in China，you can use parameter `if_use_cn_host=False` or `reset_host_url='https://translate.google.com'`.
