### ISSUE TITLE
目前仅google和youdao接口可以使用。

### ISSUE THREAD

**Issue by DaPoHou** [UlionTse/translators#9]
其他接口都报错。

**Comment by UlionTse** [comment]
@DaPoHou 请贴一下出错原因及相关代码，谢谢。

**Comment by DaPoHou** [comment]
非常抱歉，忘记贴上了，现在贴上：
sogou:

`update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.7 10`

**Comment by UlionTse** [comment]
@DaPoHou 请允许你的计算机可以调用javascript，权限或环境配置问题；alibaba和bing已经修复，请重新下载安装4.4.2版本。

**Comment by DaPoHou** [comment]
我在Debian 9和Ubuntu 18.04都不可以。
需要安装什么额外库吗？

**Comment by DaPoHou** [comment]
是的，还需要安装nodejs，希望在说明里补充上。
问题解决了。

**Comment by UlionTse** [comment]
@DaPoHou 你重新安装新版本了吗？关于js环境，PyExecjs依赖环境参考https://github.com/doloopwhile/PyExecJS

**Comment by DaPoHou** [comment]
当然，版本是4.4.2
pip install --upgrade translators

**Comment by UlionTse** [comment]
@DaPoHou 那你不使用异步，简单调用也会出错吗？建议不要频繁请求翻译接口，这样容易ip被封，导致请求出错。建议在请求参数中增加sleep_seconds值。

**Comment by DaPoHou** [comment]
是的，仍然报错。
```
import translators as ts

to_trans = '微信是个体验非常不好的工具。'
result = ts.bing(to_trans, 'auto', 'en')
print(result)
```

**Comment by UlionTse** [comment]
@DaPoHou 谢谢推荐新的翻译工具，后续会加上。关于bing这块儿，估计你那边应该是ip被封了，过段时间在调用看看。我的：
![ts-2020-03-28 185310](https://user-images.githubusercontent.com/14334826/77821508-c7522700-7125-11ea-8f74-87a8befa6b46.png)

**Comment by DaPoHou** [comment]
我在多台服务器测试都是这样错误提示。
台湾，香港，韩国，均如此。

**Comment by UlionTse** [comment]
@DaPoHou 那你应该看到我回复的我这边正常调用的截图了。如果只是alibaba和bing的问题，那我猜测是你并没有正常更新到4.4.2版本，4.4.2版本主要解决的就是这两个翻译接口的问题，点击[change_log.txt](https://github.com/UlionTse/translators/blob/master/change_log.txt)获取相关详细内容。
另外，如果你适用海外服务器，可在google和bing中设置参数`if_use_cn_host=False`。

**Comment by DaPoHou** [comment]
![aa](https://user-images.githubusercontent.com/26761596/77866437-adb7f900-7265-11ea-9ad2-90f5646be8b9.JPG)
很确定是4.4.2版本。

**Comment by UlionTse** [comment]
@DaPoHou 目前来看就是简单的被封了，你请求太频繁了。可以使用参数`proxies`和`sleep_seconds`来避免。开发者温馨提示，不建议大量密集请求。若做商业用途，请购买相关企业提供的翻译服务。
<img width="440" alt="屏幕快照 2020-03-30 下午3 44 51" src="https://user-images.githubusercontent.com/14334826/77888165-639f3980-729e-11ea-945f-7cf4231b3238.png">

**Comment by DaPoHou** [comment]
关于bing接口报错，我看这个人和我是同样错误。
https://github.com/UlionTse/translators/issues/1
