### ISSUE TITLE
Make source distribution releases available

### ISSUE THREAD

**Issue by freddyheppell** [UlionTse/translators#90]
I've been using this package for some research recently, so it would be very useful for this package to be available in on Conda Forge so it can be used in Anaconda properly. However, for the conda recipe to work, it either needs the source distribution (from `setup.py sdist`) to be uploaded to PyPI or it needs releases to be made for versions on GitHub. Currently this package has neither so it's not possible to create a Conda recipe. It would be much appreciated if one of those steps could be taken!

**Comment by UlionTse** [comment]
@freddyheppell Hello friend
It is possible but not necessary. 
Generally, conda's packages are either specially optimized by themselves or specially customized, otherwise unnecessary. PYPI is the official python package index, conda does not affect the use of pip.

**Comment by freddyheppell** [comment]
It is recommended that Pip is avoided if possible when using Conda because it is not able to track the dependencies as well, and you can't include them in your conda environment file. This makes using it as part of a Conda environment for research 

Like I said, all you need to do to make the package compatible with Conda is to either upload the source distribution to PyPI, or tag releases on GitHub, and the Conda recipe can be automatically created.

**Comment by UlionTse** [comment]
@freddyheppell Hello friend, try it. [https://anaconda.org/UlionTse/translators](https://anaconda.org/UlionTse/translators)

**Comment by freddyheppell** [comment]
Works great, thanks!

My only other suggestion is that you submit it to conda through [conda forge](https://conda-forge.org/docs/maintainer/adding_pkgs.html) instead of your own channel. Conda Forge uses recipes to automatically build and upload packages using the source distribution from PyPI. You can use the grayskull tool described on that page to generate the recipe for you as well.

You will also only need to worry about maintaining one package on Conda, since all the dependencies (except pyexecjs) are already on Forge, so you don't need to worry about ever updating them - and as PyexecJS is EOL, that won't need to be updated either. It also makes new releases much easier for you. When you release a new version, you just have to change the version number in the Forge recipe, and it builds and uploads the new version. Conda users will already be familiar with using Conda Forge, so it increases the chances of people finding your package on there and using it.

**Comment by freddyheppell** [comment]
Works great, thanks! I've noticed your PR to conda forge as well. I think the reason it hasn't been merged yet is because you still have made changes to the example meta file!

**Comment by UlionTse** [comment]
@freddyheppell After this, all checks have passed, but it is in progress or wait yet.

**Comment by freddyheppell** [comment]
If you check the files changed tab on your pull request, there are still some whitespace changes to the template file.

**Comment by UlionTse** [comment]
:sweat_smile: Corrected

**Comment by UlionTse** [comment]
God's eye! https://anaconda.org/conda-forge/translators
