### ISSUE TITLE
Google and Yandex giving errors

### ISSUE THREAD

**Issue by IveMalfunctioned** [UlionTse/translators#98]
I use this library as a part of one of my Discord bots, and for about 2 months now the translator hasn't been working. Here's a snippet of my code that uses `translators`:
`embedES=discord.Embed(description=":flag_gb: " + message.author.mention + "**:** " + ts.google(translateThis, to_language='es', inline=False), color=discord.Color.blue())
await bot.get_channel(spanish_general).send(embed=embedES)`

`translateThis` is the text input, in the case of Discord it's the message content. This code generates this error:

`raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://translate.google.cn/_/TranslateWebserverUi/data/batchexecute`

It used to work perfectly fine, so I'm just assuming Google changed something with their translator. Attempting to use Yandex instead also results in a similar error:

`raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://translate.yandex.net/api/v1/tr.json/detect?sid=725740fa.f9a42836.bb593b11.47875647d22747&srv=tr-text&text=test&hint=zh%2Cen&options=1`

Bing works just fine though, so I'll use it in the meantime

**Comment by UlionTse** [comment]
@IveMalfunctioned Hello friend!
More version information, runtime environment information, region information please.
Maybe there are some forbidden errors in `yandex()`, but `google()`  was offline in China on Oct. 2022. If you can use proxy ..., or you can use `bing()` instead.

**Comment by IveMalfunctioned** [comment]
`translators` version: 4.9.5
Region: USA
I'm not in China and am not using Chinese. The translator seems to have not been working since September 25th, 2022

I don't know what you mean by this
> runtime environment information

if you mean Python version:
`Python` version: 3.10.0

**Comment by UlionTse** [comment]
use `pip install --upgrade translators==5.5.0`

**Comment by IveMalfunctioned** [comment]
That fixed the issue. Thanks
